# Copyright Vanibels lodaria mc

global:
  name: "Lodaria "
  version: 2
  coreVersion: 1.4
  DefaultMotd: "§l§4[LODARIA] §r§6PvP-Fac §1Vanilla 1.XXX §f- §lPréparez-vous pour la V2 \!"
  EventMotd: "§l§4[LODARIA] §r§6PvP-Fac §1Vanilla 1.XXX §f- §lEvent en cour"

database:
  host: "mysql.railway.internal"
  port: "3306"
  DBName : "railway"
  user: "root"
  password: "qllLJrbhhqmnpMqoiuckPtJHePkpMsji"

# Configuration pour le mode maintenance
maintenance:
  name : "Lodaria"
  motd: "§c§lMaintenance en cours ! §ePréparez-vous pour la version 2 de Lodaria avec des nouveautés et améliorations !"
  kickMessage: "Serveur en maintenance reessayer plus tard"