name: Lodacore
version: '1.7'
main: fr.vanibels.lodacore.Lodacore
load: STARTUP
api-version: '1.20'
author: Vanibels
description: plugin principal du serveur Lodaria.
commands:
  #royaume:
  #  description: Creé un royaume
  #  aliases:
  #    - f
  #    - r
  #    - v
  vanish:
    permission: lodaria.mod.vanish.set
    description: Set vanish
    aliases:
      - v
  svanish:
    permission: lodaria.mod.vanish.set.super
    description: Set super vanish
    aliases:
      - sv
      - supervanish
  join:
    description: Reloindre le serveur
  lkit:
    description: Access kit grade.
    permission: lodaria.tools.manag
  maintenance:
    description: Gérer le mode maintenance.
    permission: lodaria.maintenance
    aliases:
      - maint
    usage: /<command>
  core:
    description: Commande du core
    permission: lodaria.admin
  sanction:
    description: Ouvrir le GUI de gestion des joueurs
    usage: /staff, ss
    aliases: ss
  tuto:
    description: tuto
    usage: /tuto
  testASOM:
    description: Dev test if plugins start
    usage: /testASOM
    permission: lodaria.tools.debug
  spawn:
    description: Tp to the spawn
    usage: /spawn
  rstaff:
    description: go to staff reunion
    usage: /rstaff
    permission: lodaria.supermod
  discord:
    usage: /discord
    description: get discord of Ascaria oneblock
  site:
    usage: /site
    description: go to the site
  bienvenue:
    description: donner les premiére instruction au nouveau joueur
    aliases:
      - bvn
    usage: /bvn {player}
  jour:
    description: Met le jour
    permission: lodaria.mod.supermod
  nuit:
    description: Met la nuit
    permission: lodaria.mod.supermod
  sun:
    description: Met la pluie sur off
    permission: lodaria.mod.supermod
  rain:
    description: Met la pluie sur on
    permission: lodaria.mod.supermod
  speedon:
    description: Met la vittesse sur 3
    permission: lodaria.mod.supermod
  speedoff:
    description: Met la vittesse sur 1
    permission: lodaria.mod.supermod

permissions:
  lodaria.mod.vanish.view:
    description: View vanised user
    default: op
  lodaria.mod.vanish.set:
    description: Set vanish
    default: op
  lodaria.mod.vanish.set.super:
    description: Set super vanish
    default: op
  lodaria.user.teleport.bypass:
    description: Bypass le cooldown et le delai avnt la teleportation
    default: op
  lodaria.cloud:
    description: Acces au command cloud
    default: op
  lodaria.cloud.info:
    description: Acces un info profil d'un joueur
    default: op
  lodaria.mod:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.chat:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.conf:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.rstaff:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.rgameplay:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.bypass:
    description: Permission d'acceder au permission de moderation
    default: op
  lodaria.mod.supermod:
    default: op
    description: permission d'acces au permission de super operateur
  lodaria.events:
    description: Permet de gérer les commandes d'annonce d'event
  lodaria.tools.debug:
    description: Permet d'accéder aux commandes administratives.
  lodaria.tools.manag:
    description: Permet d'accéder aux commandes administratives.
  lodaria.admin:
    description: Permet d'accéder aux commandes administratives.
    default: op

  lodaria.user:
    description: Permissions de base pour les utilisateurs.
    default: true

  lodaria.maintenance:
    description: Permission pour utiliser la commande de maintenance.
    default: op

  lodaria.modMessage:
    description: Permission pour écrire ét voir les messages dans le chat modérateur
    default: op

  lodaria.staff:
    description: Permission d'utiliser le /staff
    default: op
  lodaria.chatmanagers:
    description: Permission pour se mettre en vanish
    default: op